CREATE TABLE cardboardactions(id INTEGER PRIMARY KEY, action TEXT, type TEXT);
CREATE TABLE cardboardlinks(id INTEGER PRIMARY KEY, timestamp INTEGER, name TEXT, url TEXT, title TEXT, domain TEXT);
CREATE TABLE cardboardlog(id INTEGER PRIMARY KEY, timestamp INTEGER, name TEXT, message TEXT);
CREATE TABLE cardboardnick(id INTEGER PRIMARY KEY, jid TEXT, nick TEXT, timestamp INTEGER DEFAULT 0);
CREATE INDEX cardboardlinks_name_ix ON cardboardlinks(name);
CREATE INDEX cardboardlinks_timestamp_ix on cardboardlinks(timestamp);
CREATE INDEX cardboardlog_name_ix ON cardboardlog(name);
CREATE INDEX cardboardlog_timestamp_ix on cardboardlog(timestamp);
CREATE INDEX cardboardnick_jid_ix on cardboardnick(jid);
CREATE INDEX cardboardnick_nick_ix on cardboardnick(nick);
CREATE INDEX cardboardnick_nick_ix_nocase on cardboardnick(nick COLLATE NOCASE);
